# Generated by Django 4.0.4 on 2022-04-29 10:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(help_text='The name of the job', max_length=255, verbose_name='job name')),
                ('po_number', models.CharField(help_text='The PO Number for this jon', max_length=255, verbose_name='PO Number')),
                ('spo_number', models.CharField(blank=True, help_text="The Suppier's PO Number for this jon", max_length=255, verbose_name='Supplier PO Number')),
                ('description', models.TextField(help_text='A description of the load', null=True, verbose_name='description')),
                ('notes', models.TextField(blank=True, help_text='Any notes about this load', verbose_name='notes')),
                ('created_when', models.DateTimeField(default=datetime.datetime.now, help_text='The date this historical entry was created', verbose_name='created')),
                ('updated_when', models.DateTimeField(default=datetime.datetime.now, help_text='When the load was updated', verbose_name='when updated')),
                ('do_install', models.BooleanField(default=False, help_text='If Ervin will be doing the installation', verbose_name='Do Install')),
                ('photo', models.ImageField(blank=True, help_text='A photo of the load', null=True, upload_to='', verbose_name='photo')),
            ],
            options={
                'ordering': ('updated_when',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The status of the load', max_length=80)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The supplier's name", max_length=150)),
                ('details', models.TextField(blank=True, help_text='Any details such as contact info', verbose_name='details')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The status of the load', max_length=50)),
                ('rank', models.IntegerField(default=1000, help_text='The order that this status should display in a list of statuses', verbose_name='rank')),
                ('recipients', models.ManyToManyField(blank=True, help_text='The recipients of notices for when a load changes to this status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('rank', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LoadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_when', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, help_text='The data that was submitted for this change', verbose_name='data')),
                ('load', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ervinloads.load')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='load',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The location of this load', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ervinloads.location'),
        ),
        migrations.AddField(
            model_name='load',
            name='status',
            field=models.ForeignKey(blank=True, help_text='The status of the load', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ervinloads.status'),
        ),
        migrations.AddField(
            model_name='load',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='The supplier of this load', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ervinloads.supplier'),
        ),
    ]
