# Generated by Django 4.0.4 on 2022-04-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervinloads', '0002_alter_load_do_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='completion_status',
            field=models.IntegerField(blank=True, help_text='Status of the installation', null=True, verbose_name='completion status'),
        ),
    ]
