# Generated by Django 4.0.4 on 2022-04-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervinloads', '0003_load_completion_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadhistory',
            options={'ordering': ('-changed_when',)},
        ),
        migrations.AddField(
            model_name='status',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If this status is for an active load (one that is not yet complete or canceled and should be displayed in the default list)', verbose_name='is active'),
        ),
    ]
