# Generated by Django 4.0.4 on 2022-05-01 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ervinloads', '0004_alter_loadhistory_options_status_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='completion_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Active'), (1, 'Complete'), (2, 'Backordered')], help_text='Status of the installation', null=True, verbose_name='completion status'),
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The status of the load', max_length=50)),
                ('rank', models.IntegerField(default=1000, help_text='The order that this status should display in a list of statuses', verbose_name='rank')),
                ('is_active', models.BooleanField(default=False, help_text='If this status is for an active load (one that is not yet complete or canceled and should be displayed in the default list)', verbose_name='is active')),
                ('recipients', models.ManyToManyField(blank=True, help_text='The recipients of notices for when a load changes to this status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='load',
            name='completion_status_model',
            field=models.ForeignKey(help_text='The completion status of this load', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ervinloads.completion'),
        ),
    ]
