# Generated by Django 4.0.4 on 2022-05-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ervinloads', '0005_alter_load_completion_status_completion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completion',
            options={'ordering': ('rank',)},
        ),
        migrations.RenameField(
            model_name='load',
            old_name='completion_status_model',
            new_name='completion',
        ),
        migrations.RemoveField(
            model_name='load',
            name='completion_status',
        ),
    ]
