# Generated by Django 4.0.4 on 2022-05-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervinloads', '0006_alter_completion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='deleted_when',
            field=models.DateTimeField(blank=True, help_text='If this item is deleted, when', null=True, verbose_name='deleted when'),
        ),
    ]
