# Generated by Django 4.0.4 on 2022-05-01 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ervinloads', '0007_load_deleted_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='do_install',
            field=models.IntegerField(choices=[(0, 'NA/Unkown'), (1, 'Deliver'), (2, 'Install')], default=0, help_text='If Ervin will be doing the installation', verbose_name='Do Install'),
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this notification group', max_length=80, verbose_name='name')),
                ('email_addresses', models.TextField(blank=True, help_text='Send to the following email addresses(comma or semicolon separated)', verbose_name='email addresses')),
                ('is_default', models.BooleanField(default=False, help_text='If this is a default notification group for new loads', verbose_name='is_default')),
                ('users', models.ManyToManyField(blank=True, help_text='Send to the following users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='load',
            name='notification_groups',
            field=models.ManyToManyField(blank=True, help_text='Notification groups that should be notified about changes to this load', to='ervinloads.notificationgroup'),
        ),
    ]
