# Generated by Django 4.0.4 on 2022-05-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ervinloads', '0008_alter_load_do_install_notificationgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationgroup',
            options={'ordering': ('-is_default', 'name')},
        ),
        migrations.RemoveField(
            model_name='notificationgroup',
            name='users',
        ),
        migrations.AddField(
            model_name='completion',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If this is the default status for new loads (Only one will used even if more than one is selected)', verbose_name='is default'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If this is the default location for new loads (Only one will used even if more than one is selected)', verbose_name='is default'),
        ),
        migrations.AddField(
            model_name='status',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If this is the default status for new loads (Only one will used even if more than one is selected)', verbose_name='is default'),
        ),
        migrations.AlterField(
            model_name='load',
            name='location',
            field=models.ForeignKey(help_text='The location of this load', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ervinloads.location'),
        ),
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.ForeignKey(help_text='The status of the load', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ervinloads.status'),
        ),
    ]
