# Generated by Django 4.0.4 on 2022-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervinloads', '0009_alter_notificationgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completion',
            options={'ordering': ('-is_default', 'rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-is_default', 'name')},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('-is_default', 'rank', 'name')},
        ),
        migrations.AlterField(
            model_name='load',
            name='do_install',
            field=models.IntegerField(choices=[(0, 'NA/Unkown'), (1, 'Deliver'), (2, 'Install')], default=1, help_text='If Ervin will be doing the installation', verbose_name='Do Install'),
        ),
    ]
