# Generated by Django 4.0.4 on 2022-05-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ervinloads', '0010_alter_completion_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_when', models.DateField(blank=True, help_text='The date this notification was created', null=True, verbose_name='created when')),
                ('load', models.ForeignKey(help_text='The load about which to notify', on_delete=django.db.models.deletion.CASCADE, to='ervinloads.load')),
            ],
        ),
    ]
