# Generated by Django 4.0.4 on 2022-05-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervinloads', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, default='Created', help_text='The action (Created, Updated) to be reported', max_length=30, verbose_name='action'),
        ),
    ]
