# Generated by Django 4.0.4 on 2022-05-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervinloads', '0012_notification_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, help_text='The action (Created, Updated) to be reported', max_length=30, verbose_name='action'),
        ),
    ]
