# Generated by Django 4.0.4 on 2022-05-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervinloads', '0013_alter_notification_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A description of the load', verbose_name='description'),
            preserve_default=False,
        ),
    ]
