# Generated by Django 4.0.4 on 2022-05-08 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ervinloads', '0014_alter_load_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='DeliveryStatus',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='The location of the load', max_length=80),
        ),
        migrations.RenameField(
            model_name='load',
            old_name='status',
            new_name='delivery_status',
        ),
    ]
