# Generated by Django 4.1 on 2022-08-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ervinloads', '0016_rename_completion_completionstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completionstatus',
            options={'ordering': ('rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='deliverystatus',
            options={'ordering': ('rank', 'name')},
        ),
        migrations.RemoveField(
            model_name='completionstatus',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='deliverystatus',
            name='recipients',
        ),
    ]
